[versions]
agp = "8.4.2"
firebaseAuth = "23.0.0"
firebaseAuthVersion = "21.0.1"
firebaseDatabase = "21.0.0"
glide = "4.15.1"
googleServices = "4.4.2"
googleServicesVersion = "4.3.10"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-v2101 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseDatabase" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
google-services-v4310 = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

